language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "6"
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"
  - "0.10"

install:
  - sudo apt-get autoremove -fy
  - wget https://files.appneta.com/install_appneta.sh
  - sudo sh ./install_appneta.sh f08da708-7f1c-4935-ae2e-122caf1ebe31
  - sudo apt-get install libkrb5-dev
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE test; USE test; CREATE TABLE test (foo varchar(255));'
  - "echo \"create keyspace test with replication = {'class':'SimpleStrategy','replication_factor':1};\" | /usr/local/cassandra/bin/cqlsh --cqlversion=3.0.3"
  - npm install
  - npm run install-deps || true

script: "npm test"

services:
  - cassandra
  - mongodb
  - redis
  - memcached
  - rabbitmq

# Support io.js 3.x and node 4.x+
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
