language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "1.1"
  - "1.0"
  - "0.12"
  - "0.10"
  - "0.8"

install:
  - wget https://files.appneta.com/install_appneta.sh
  - sudo sh ./install_appneta.sh f08da708-7f1c-4935-ae2e-122caf1ebe31

before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE test; USE test; CREATE TABLE test (foo varchar(255));'
  - "echo \"create keyspace test with replication = {'class':'SimpleStrategy','replication_factor':1};\" | /usr/local/cassandra/bin/cqlsh --cqlversion=3.0.3"
  - if [[ "`node --version`" =~ ^v0.8* ]]; then npm -g install npm; fi
  - npm install
  - npm install leveldown

script: "npm test"

services:
  - cassandra
  - mongodb
  - redis
  - memcached

matrix:
  allow_failures:
