language: node_js

env:
    global:
    - APPOPTICS_REPORTER=udp
    - APPOPTICS_REPORTER_UDP=localhost:7832

branches:
  only:
    - per-request-bis
    # slightly modified from https://github.com/sindresorhus/semver-regex
    - /^v?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\dA-Za-z-]+(?:\.[\dA-Za-z-]+)*)?(?:\+[\dA-Za-z-]+(?:\.[\dA-Za-z-]+)*)$/


cache:
  directories:
  - node_modules

node_js:
  - "9"
  - "8"
  - "6"
  - "4"

install:
  - sudo apt-get autoremove -fy
  - sudo apt-get install libkrb5-dev
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE test; USE test; CREATE TABLE test (foo varchar(255));'
#  - "echo \"create keyspace test with replication = {'class':'SimpleStrategy','replication_factor':1};\" | /usr/local/cassandra/bin/cqlsh --cqlversion=3.0.3"
  - curl -s https://bb2874f186eb519f73ff3f8c64a777be6522ac88490ed0ca:@packagecloud.io/install/repositories/AppOptics/apm-node/script.node.sh | force_npm=1 bash
  - npm install
  - npm install appoptics-bindings
  - npm run install-deps || true

script: "npm test"

services:
#  - cassandra
  - mongodb
  - redis
  - memcached
  - rabbitmq

# Support io.js 3.x and node 4.x+
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
