# supporting backends for node-appoptics testing
version: '2.1'

services:
  main:
    build:
      context: .
      args:
        # expect librato/node-appoptics-bindings#new-liboboe while private
        - AO_TEST_PACKAGE
        # expect a git auth token (or extend Dockerfile with user and password)
        - AO_TEST_GITAUTH
        # - AO_TEST_GITUSER
        # - AO_TEST_GITPASS
    image: ao-test-main
    logging:
      options:
        max-file: "1"
        max-size: 50m
    command: ["/usr/bin/tracelyzer", "-L 0.0.0.0", "-r"]
  redis:
    image: "redis"
    build:
      context: test/docker/
      dockerfile: redis.yml
    logging:
      options:
        max-file: "1"
        max-size: 50m
